try:
    print(x)
    print('try')
except: #if try is false then execute except
    print("error occured")
finally:  #default option 
    print(33+3)
###used for handle the errors which is called exception handling

##print(x)
##print("welcome")
